// This file is generated by Prismic local builder. Update with care!

export { default as MySlice } from './MySlice'
export { default as PostCardWithoutImage } from './PostCardWithoutImage'
export { default as PostsCards } from './PostsCards'
